name: Run Bambda Checker on Pull Request

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Validate Bambdas
        run: |
          [ $(sha256sum BambdaChecker-1.5.jar | awk '{ print $1 }') = '7720217e95d5b3f167dff73c446f776be5f9618b8e6db38bbec544b1b09169ac' ]
          java -jar BambdaChecker-1.5.jar validateonly
