name: Run Bambda Checker Manually

on: [workflow_dispatch]

jobs:
  update_readmes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          ssh-key: ${{secrets.ACTION_PRIVKEY}}
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Validate Bambdas & update READMEs
        run: |
          [ $(sha256sum BambdaChecker-1.4.jar | awk '{ print $1 }') = 'f8df4971c990c016ba0a076a8cc49fd3323ef9f883f52c98290b40dacd75aed6' ]
          java -jar BambdaChecker-1.4.jar
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Update README.md files" || true
          git push || true
