name: Run Bambda Checker on Pull Request

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Validate Bambdas
        run: |
          [ $(sha256sum BambdaChecker-1.4.jar | awk '{ print $1 }') = '1c18afc1cca105403158a220b99c389cffb110068a659f4b269f5797b47cc98f' ]
          java -jar BambdaChecker-1.4.jar validateonly
